### ISSUE TITLE
Adding keyboard shortcuts and allow double clicking PRCs in Windows Explorer

### ISSUE THREAD

**Issue by zrksyd** [BenHall-7/paracobNET#14]
Adding the ability to open and save PRC's with Ctrl + O and Ctrl + S and opening prcEditor by double clicking a PRC. (I don't know the technical name for this, but I think it has to do with running the PRC has an argument of prcEditor.exe)

**Comment by BenHall-7** [comment]
Second request is actually already a feature. The way you would do this on Windows is by either double clicking a filetype with no default program associated with it, then choosing prcEditor as the default.
If the file opens in something else by default, you should instead right click, select “Open With”, and choose prcEditor.

**Comment by BenHall-7** [comment]
Added this!
